<?php
namespace Admin\Model;
use Think\Model\RelationModel;
class OrderExtendModel extends RelationModel {

    protected $_validate = array(
        array('couriernumber','require','快递单号不能为空！'), //默认情况下用正则进行验证
    );

    protected $_map = array(
        
    );

    protected $_auto = array(
        array('addjson','setjson',3,'callback'),
    );

    protected $_link = array(
        
    );

    protected function setjson(){
        return htmlspecialchars_decode(I('post.addjson'));
    }

    /**
     * 开发者：huangwei
     * 方法功能： 发送一条信息到用户微信
     * @param $data
     * @param $options
     */
    protected function _after_insert($data, $options)
    {
        parent::_after_insert($data, $options); // TODO: Change the autogenerated stub

        $order = D('order')->where(array('orderid'=>$data['orderid']))->relation(array('snop','user','extend'))->find();
        $order['snop'][0]['snopjson'] = json_decode($order['snop'][0]['snopjson'],true);
        A('Home/weixin')->send_message_fahuo($order);
    }

}